### ISSUE TITLE
False unused alert for webpack-and babel plugins

### ISSUE THREAD

**Issue by Zerim** [depcheck/depcheck#143]
Thanks for the great module! (Saved me a lot of time this morning). Adding a few issues to your list of false alerts.

This issue refers to plugin based modules. Specifically in the repo I'm working with, modules that follow the `babel-*` or `*-loader` naming convention, which are loaded automatically and crucial to the build process even if they are not required/imported.

**Comment by lijunle** [comment]
Hi @Zerim , glad to hear this tool is helping you.

1. How do you use the babel plugins? This tool will detect the plugins listed in `.babelrc` file.
2. For the webpack loader. They must be list in `webpack.config.js` file. The filename is critical.

How is your case? Could you please provide more details?

**Comment by Zerim** [comment]
Ah I think the naming is the issue then. Our webpack config files are called `webpack.development.config.js` and `webpack.production.config.js` ... I think this pattern is not uncommon for webpack setups. Not sure what the best solution is, maybe to allow us to specify this as a comand-line agument.

**Comment by cnolimit** [comment]
@lijunle have the suggestions made by @Zerim been implemented? or is there an alternative way to removing them from the output and avoiding the strict naming convention?

**Comment by lijunle** [comment]
I am fine to change the name check in [this line](https://github.com/depcheck/depcheck/blob/master/src/special/webpack.js#L43). Do we have some naming convention here? `/webpack\..*\.config.js/`?

**Comment by lijunle** [comment]
I published version 0.6.6 to support webpack config name with regex `/webpack(\..+)?\.config.js/`. Please test it and give feedbacks. Again, thank you for reporting this. 👍

**Comment by wesleymostien** [comment]
my webpack config is in "webpack.config.js" file on the root but I still have alerts.
using : npm-check --specials bin,webpack

**Comment by MattWThomas** [comment]
I still have this same issue in the current version

**Comment by dcakirkaya** [comment]
Same issue, my webpack config file is called "webpack.config.js" and --specials=babel,bin,eslint,husky,jest,prettier,webpack
using depcheck 1.4.0

**Comment by joeyparis** [comment]
Can we have a way to specify the webpack config path? Mine is nested and follows a different path (e.g. `internals/webpack/webpack.prod.babel.js`)
