### ISSUE TITLE
Installed peer dependencies are marked as unused

### ISSUE THREAD

**Issue by remcohaszing** [depcheck/depcheck#181]
For example, `babel-core` is a peer dependency of `babel-loader`. It should not be marked as unused. The same goes for `jasmine-core` and `karma-jasmine`.

There are probably many more similar cases.

**Comment by lijunle** [comment]
Hi, @remcohaszing

Thanks for reporting issues for depcheck. Which version of node and npm are you using?

**Comment by remcohaszing** [comment]
```
$ node --version
v7.1.0
$ npm --version
4.0.2
```

**Comment by Matt-Webb** [comment]
I am also seeing the same issue.

``` 
$ node --version
v4.4.4
$ npm --v
v 2.15.1
```
 Note: I am using Webpack (v1.13.2) as my module builder.

**Comment by lijunle** [comment]
@remcohaszing It is strange, the peer dependencies should be supported. Which version of depcheck are you running?

@Matt-Webb If it is related to webpack, what is your file name of webpack config? Currently, it is hard code as `webpack.config.js` (related to https://github.com/depcheck/depcheck/issues/143).

**Comment by remcohaszing** [comment]
I'm using `depcheck@0.6.5`.

Note that `babel-core` is marked as unused, not `babel-loader`.

***webpack.config.js***:

```js
const path = require('path');

const HtmlWebpackPlugin = require('html-webpack-plugin');

const pkg = require('./package.json');


module.exports = {
  entry: path.resolve(__dirname, './app/main.jsx'),
  output: {
    path: path.resolve(__dirname, 'build/'),
    filename: 'gallery.js'
  },
  resolve: {
    extensions: ['', '.js', '.jsx']
  },
  devServer: {
    contentBase: path.resolve(__dirname, 'app')
  },
  devtool: 'inline-source-map',
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        loader: 'babel',
        exclude: /node_modules/
      },
      {
        test: /\.json$/,
        loader: 'json'
      },
      {
        test: /\.css$/,
        loaders: ['style', 'css']
      },
      {
        test: /\.(eot|gif|jpe?g|png|svg|ttf|woff2?)(\?.*)?$/,
        loaders: ['file']
      }
    ]
  },
  externals: {
    // Workaround for https://github.com/airbnb/enzyme/issues/47
    'react/addons': true,
    'react/lib/ExecutionEnvironment': true,
    'react/lib/ReactContext': true
  },
  plugins: [
    new HtmlWebpackPlugin({
      title: pkg.name
    })
  ]
};
```

**Comment by lijunle** [comment]
Thank you @remcohaszing , I identify it as a bug. 

Bascially, it is caused by the webpack detector [returns an array](https://github.com/depcheck/depcheck/blob/master/src/special/webpack.js#L49) as dependencies, For the such case, depcheck [directly returns the array](https://github.com/depcheck/depcheck/blob/master/src/check.js#L102) as dependencies without drill out its peer dependencies and optional dependencies.

**Comment by lijunle** [comment]
*Update*: I published version 0.6.6 to resolve this issue. Please test it. Again, thank you for reporting this. 👍

**Comment by remcohaszing** [comment]
It works! Thanks :smile:

**Comment by robross0606** [comment]
This still appears to be happening.  My project has a peer dependency on `prom-client`:
```
npm WARN prometheus-gc-stats@0.5.1 requires a peer of prom-client@>= 10 < 12 but none is installed. You must install peer dependencies yourself.
```
However, `depcheck` lists it as unused:
```
C:\Code\code>depcheck --version
1.4.0

C:\Code\code>depcheck
Unused dependencies
* prom-client
```
